# coding: utf-8

# flake8: noqa
"""
    MÁV API

    Unofficial API for MÁV - Hungarian Railways

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from vonatinfo_client.models.get_data_post200_response import GetDataPost200Response
from vonatinfo_client.models.get_data_post_request import GetDataPostRequest
from vonatinfo_client.models.station_request import StationRequest
from vonatinfo_client.models.station_request_jo import StationRequestJo
from vonatinfo_client.models.station_result import StationResult
from vonatinfo_client.models.station_result_d import StationResultD
from vonatinfo_client.models.station_result_d_param import StationResultDParam
from vonatinfo_client.models.train import Train
from vonatinfo_client.models.train_request import TrainRequest
from vonatinfo_client.models.train_request_jo import TrainRequestJo
from vonatinfo_client.models.train_result import TrainResult
from vonatinfo_client.models.train_result_d import TrainResultD
from vonatinfo_client.models.train_result_d_param import TrainResultDParam
from vonatinfo_client.models.train_result_d_result import TrainResultDResult
from vonatinfo_client.models.train_schedule_request import TrainScheduleRequest
from vonatinfo_client.models.train_schedule_request_param import TrainScheduleRequestParam
from vonatinfo_client.models.train_schedule_result import TrainScheduleResult
from vonatinfo_client.models.train_schedule_result_d import TrainScheduleResultD
from vonatinfo_client.models.trains_request import TrainsRequest
from vonatinfo_client.models.trains_request_jo import TrainsRequestJo
from vonatinfo_client.models.trains_result import TrainsResult
from vonatinfo_client.models.trains_result_d import TrainsResultD
from vonatinfo_client.models.trains_result_d_param import TrainsResultDParam
from vonatinfo_client.models.trains_result_d_result import TrainsResultDResult
from vonatinfo_client.models.trains_result_d_result_trains import TrainsResultDResultTrains
