# Generated by Django 5.1.3 on 2024-11-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("arrival", "Arrival"), ("departure", "Departure")],
                        max_length=50,
                    ),
                ),
                ("station_name", models.CharField(max_length=100)),
                ("station_code", models.CharField(max_length=50)),
                ("scheduled_arrival", models.DateTimeField()),
                ("scheduled_departure", models.DateTimeField()),
                ("actual_or_estimated_arrival", models.DateTimeField(null=True)),
                ("actual_or_estimated_departure", models.DateTimeField(null=True)),
                ("train_name", models.CharField(max_length=50, null=True)),
                ("train_number", models.CharField(max_length=50)),
                ("train_id", models.CharField(max_length=50)),
                ("relation_symbol", models.CharField(max_length=50, null=True)),
                ("kind_name", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
