# coding: utf-8

# flake8: noqa
"""
    MÁV ELVIRA API

    Unofficial API for MÁV ELVIRA - Hungarian Railways (jegy.mav.hu)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from elvira_client.models.havarian_infok import HavarianInfok
from elvira_client.models.kind import Kind
from elvira_client.models.modality import Modality
from elvira_client.models.modality_sign import ModalitySign
from elvira_client.models.scheduler import Scheduler
from elvira_client.models.service import Service
from elvira_client.models.sign import Sign
from elvira_client.models.sign1 import Sign1
from elvira_client.models.station import Station
from elvira_client.models.station_scheduler_details import StationSchedulerDetails
from elvira_client.models.timetable_request import TimetableRequest
from elvira_client.models.timetable_response import TimetableResponse
from elvira_client.models.viszonylat_object import ViszonylatObject
from elvira_client.models.viszonylati_jel import ViszonylatiJel
