# coding: utf-8

"""
    MÁV ELVIRA API

    Unofficial API for MÁV ELVIRA - Hungarian Railways (jegy.mav.hu)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from elvira_client.models.sign1 import Sign1
from typing import Optional, Set
from typing_extensions import Self

class RelationSymbol(BaseModel):
    """
    Relation symbol
    """ # noqa: E501
    piktogram_full_name: Optional[StrictStr] = Field(alias="piktogramFullName")
    font_szin_kod: StrictStr = Field(alias="fontSzinKod")
    hatter_szin_kod: StrictStr = Field(alias="hatterSzinKod")
    sign: Sign1
    jel: StrictStr = Field(description="Textual relation symbol")
    __properties: ClassVar[List[str]] = ["piktogramFullName", "fontSzinKod", "hatterSzinKod", "sign", "jel"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RelationSymbol from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sign
        if self.sign:
            _dict['sign'] = self.sign.to_dict()
        # set to None if piktogram_full_name (nullable) is None
        # and model_fields_set contains the field
        if self.piktogram_full_name is None and "piktogram_full_name" in self.model_fields_set:
            _dict['piktogramFullName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RelationSymbol from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "piktogramFullName": obj.get("piktogramFullName"),
            "fontSzinKod": obj.get("fontSzinKod"),
            "hatterSzinKod": obj.get("hatterSzinKod"),
            "sign": Sign1.from_dict(obj["sign"]) if obj.get("sign") is not None else None,
            "jel": obj.get("jel")
        })
        return _obj


