# coding: utf-8

"""
    MÁV ELVIRA API

    Unofficial API for MÁV ELVIRA - Hungarian Railways (jegy.mav.hu)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from elvira_client.models.station_scheduler_details import StationSchedulerDetails
from typing import Optional, Set
from typing_extensions import Self

class TimetableResponse(BaseModel):
    """
    TimetableResponse
    """ # noqa: E501
    train_scheduler_details: Optional[StrictStr] = Field(alias="trainSchedulerDetails")
    station_scheduler_details: StationSchedulerDetails = Field(alias="stationSchedulerDetails")
    route_scheduler_details: Optional[StrictStr] = Field(alias="routeSchedulerDetails")
    __properties: ClassVar[List[str]] = ["trainSchedulerDetails", "stationSchedulerDetails", "routeSchedulerDetails"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TimetableResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of station_scheduler_details
        if self.station_scheduler_details:
            _dict['stationSchedulerDetails'] = self.station_scheduler_details.to_dict()
        # set to None if train_scheduler_details (nullable) is None
        # and model_fields_set contains the field
        if self.train_scheduler_details is None and "train_scheduler_details" in self.model_fields_set:
            _dict['trainSchedulerDetails'] = None

        # set to None if route_scheduler_details (nullable) is None
        # and model_fields_set contains the field
        if self.route_scheduler_details is None and "route_scheduler_details" in self.model_fields_set:
            _dict['routeSchedulerDetails'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TimetableResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "trainSchedulerDetails": obj.get("trainSchedulerDetails"),
            "stationSchedulerDetails": StationSchedulerDetails.from_dict(obj["stationSchedulerDetails"]) if obj.get("stationSchedulerDetails") is not None else None,
            "routeSchedulerDetails": obj.get("routeSchedulerDetails")
        })
        return _obj


